version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://<username>:<password>@<cluster>.mongodb.net/virtualTutor
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRE=30d
      - CORS_ORIGIN=http://localhost:80
      - SOCKET_CORS_ORIGIN=http://localhost:80
    restart: always
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_SOCKET_URL=http://localhost:5000
    restart: always
